version: '3'
services:

  ##############################################################################
  #                                   PELIPPER                                 #
  ##############################################################################
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports: 
      - 1025:1025
      - 8025:8025
    networks:
      - pelipper-network

  pelipper:
    image: ghcr.io/antartical/pelipper
    container_name: pelipper
    ports:
      - "9000:9000"
    environment:
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USER=admin
      - SMTP_PASSWORD=admin
    networks:
      - pelipper-network

  ##############################################################################
  #                                 DATABASE                                   #
  ##############################################################################
  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=frodo
    ports:
      - "5432:5432"
    volumes:
      - antartical.frodo:/var/lib/postgresql/data
    networks:
      - gandalf-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - gandalf-network

  ##############################################################################
  #                                 GANDALF                                    #
  ##############################################################################
  gandalf:
    build:
      context: .
      dockerfile: build/docker/dockerfile.local
    container_name: gandalf
    restart: always
    command: "gin --appPort 9000 --all -i run main.go"
    volumes:
      - ./:/api/
    ports:
      - "9100:9100"
    env_file:
      - ./build/env/.env
    networks:
      - gandalf-network
      - pelipper-network

################################################################################
#                                   NETWORKS                                   #
################################################################################
networks:
  gandalf-network:
    driver: bridge
  pelipper-network:
    driver: bridge
