// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/apps": {
            "post": {
                "security": [
                    {
                        "OAuth2AccessCode": [
                            "app:me:write"
                        ]
                    }
                ],
                "description": "creates an app",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "App"
                ],
                "summary": "Creates a new app",
                "operationId": "app-create",
                "parameters": [
                    {
                        "description": "Creates an app",
                        "name": "app",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.AppCreateData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/serializers.AppSerializer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            }
        },
        "/apps/public/{clientID}": {
            "get": {
                "description": "get an app by his clientID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "App"
                ],
                "summary": "Get an app",
                "operationId": "app-read-client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializers.AppPublicSerializer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            }
        },
        "/apps/{uuid}": {
            "get": {
                "security": [
                    {
                        "OAuth2AccessCode": [
                            "app:all:read"
                        ]
                    }
                ],
                "description": "get an app by his uuid",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "App"
                ],
                "summary": "Get an app",
                "operationId": "app-read",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializers.AppSerializer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Logs an user into the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login admin",
                "operationId": "auth-login",
                "parameters": [
                    {
                        "description": "Logs into the system with the given credentials",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.Credentials"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializers.TokensSerializer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Refresh the given access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh",
                "operationId": "auth-refresh",
                "parameters": [
                    {
                        "description": "Refresh the given access token with the refresh one",
                        "name": "tokens",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.AuthTokens"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializers.TokensSerializer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "security": [
                    {
                        "OAuth2AccessCode": [
                            "user:me:read"
                        ]
                    }
                ],
                "description": "get the user who performs the request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Me"
                ],
                "summary": "Get me",
                "operationId": "me-read",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializers.UserSerializer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "OAuth2AccessCode": [
                            "user:me:delete"
                        ]
                    }
                ],
                "description": "deletes the user who perform the request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Me"
                ],
                "summary": "Delete me",
                "operationId": "me-delete",
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "OAuth2AccessCode": [
                            "user:me:write"
                        ]
                    }
                ],
                "description": "update me",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Me"
                ],
                "summary": "Update me",
                "operationId": "me-update",
                "parameters": [
                    {
                        "description": "Updates the user with the given data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.UserUpdateData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializers.UserSerializer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            }
        },
        "/me/apps": {
            "get": {
                "security": [
                    {
                        "OAuth2AccessCode": [
                            "app:me:read"
                        ]
                    }
                ],
                "description": "Get user's created apps",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Me"
                ],
                "summary": "Get user's created apps",
                "operationId": "me-apps",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "cursor's page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "cursor's limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializers.PaginatedAppsSerializer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            }
        },
        "/me/connected-apps": {
            "get": {
                "security": [
                    {
                        "OAuth2AccessCode": [
                            "app:me:read"
                        ]
                    }
                ],
                "description": "Get user's connected apps",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Me"
                ],
                "summary": "Get user's connected apps",
                "operationId": "me-connected-apps",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "cursor's page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "cursor's limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializers.PaginatedAppsPublicSerializer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            }
        },
        "/me/reset-password": {
            "post": {
                "security": [
                    {
                        "OAuth2AccessCode": [
                            "user:me:change-password"
                        ]
                    }
                ],
                "description": "Reset my password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Me"
                ],
                "summary": "Reset my password",
                "operationId": "me-reset-password",
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            }
        },
        "/me/verify": {
            "post": {
                "security": [
                    {
                        "OAuth2AccessCode": [
                            "user:me:verify"
                        ]
                    }
                ],
                "description": "Verify me",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Me"
                ],
                "summary": "Verify me",
                "operationId": "me-verify",
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            }
        },
        "/notifications/emails/reset-password": {
            "post": {
                "description": "Sends reset password email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notification"
                ],
                "summary": "Sends reset password email",
                "operationId": "notifications-emails-reset-password",
                "parameters": [
                    {
                        "description": "resend the reset password email",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.UserResendEmail"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            }
        },
        "/notifications/emails/verify": {
            "post": {
                "description": "Sends verification email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notification"
                ],
                "summary": "Sends verification email",
                "operationId": "notifications-emails-verification",
                "parameters": [
                    {
                        "description": "sends the verification email",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.UserResendEmail"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            }
        },
        "/oauth/authorize": {
            "post": {
                "security": [
                    {
                        "OAuth2AccessCode": [
                            "user:me:authorized-app"
                        ]
                    }
                ],
                "description": "authorize app",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Oauth"
                ],
                "summary": "Authorize an app to get the user data",
                "operationId": "oauth-authorize",
                "parameters": [
                    {
                        "description": "Authorize app to get user's data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.OauthAuthorizeData"
                        }
                    }
                ],
                "responses": {
                    "302": {
                        "description": ""
                    }
                }
            }
        },
        "/oauth/login": {
            "post": {
                "description": "logs an user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Oauth"
                ],
                "summary": "Login an user and retrieve auth token",
                "operationId": "oauth-login",
                "parameters": [
                    {
                        "description": "Logs an user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.Credentials"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/serializers.TokensSerializer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            }
        },
        "/oauth/token": {
            "post": {
                "description": "Retrieves access token form the authorization one",
                "consumes": [
                    "application/x-www-form-urlencoded",
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Oauth"
                ],
                "summary": "Retrieves access token form the authorization one",
                "operationId": "oauth-token",
                "parameters": [
                    {
                        "description": "Token exchange data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.OauthExchangeToken"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/serializers.TokensSerializer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "ping the system to healthcare purposes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Ping",
                "operationId": "ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.pong"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "Creates a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create User",
                "operationId": "user-create",
                "parameters": [
                    {
                        "description": "Creates a new user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.UserCreateData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/serializers.UserSerializer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            }
        },
        "/users/{uuid}": {
            "get": {
                "security": [
                    {
                        "OAuth2AccessCode": [
                            "user:all:read"
                        ]
                    }
                ],
                "description": "get an user by his uuid",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get an user",
                "operationId": "user-read",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializers.UserSerializer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/helpers.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.pong": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string",
                    "example": "pong"
                }
            }
        },
        "helpers.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "error": {
                    "type": "string",
                    "example": "status bad request"
                }
            }
        },
        "serializers.AppPublicSerializer": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/serializers.appPublicDataSerializer"
                },
                "type": {
                    "type": "string",
                    "example": "app"
                }
            }
        },
        "serializers.AppSerializer": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/serializers.appDataSerializer"
                },
                "type": {
                    "type": "string",
                    "example": "app"
                }
            }
        },
        "serializers.CursorSerializer": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/serializers.cursorDataSerializer"
                },
                "type": {
                    "type": "string",
                    "example": "cursor"
                }
            }
        },
        "serializers.PaginatedAppsPublicSerializer": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/serializers.appPublicDataSerializer"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/serializers.paginatedAppsSerializerMeta"
                },
                "type": {
                    "type": "string",
                    "example": "app"
                }
            }
        },
        "serializers.PaginatedAppsSerializer": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/serializers.appDataSerializer"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/serializers.paginatedAppsSerializerMeta"
                },
                "type": {
                    "type": "string",
                    "example": "app"
                }
            }
        },
        "serializers.TokensSerializer": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
                },
                "expires_in": {
                    "type": "integer",
                    "example": 3600
                },
                "refresh_token": {
                    "type": "string",
                    "example": "kpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyf"
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "serializers.UserSerializer": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/serializers.userDataSerializer"
                },
                "type": {
                    "type": "string",
                    "example": "user"
                }
            }
        },
        "serializers.appDataSerializer": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "4722679b-5a48-4e85-9084-605e8df610f4"
                },
                "client_secret": {
                    "type": "string",
                    "example": "iuhgf3874tiu34gtwerbguv3iu74"
                },
                "icon_url": {
                    "type": "string",
                    "example": "https://rb.gy/1akgfo"
                },
                "name": {
                    "type": "string",
                    "example": "MyApp"
                },
                "redirect_urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "http://localhost:/callback"
                    ]
                },
                "uuid": {
                    "type": "string",
                    "example": "4722679b-5a48-4e85-9084-605e8df610f4"
                }
            }
        },
        "serializers.appPublicDataSerializer": {
            "type": "object",
            "properties": {
                "icon_url": {
                    "type": "string",
                    "example": "https://rb.gy/1akgfo"
                },
                "name": {
                    "type": "string",
                    "example": "MyApp"
                },
                "uuid": {
                    "type": "string",
                    "example": "4722679b-5a48-4e85-9084-605e8df610f4"
                }
            }
        },
        "serializers.cursorDataSerializer": {
            "type": "object",
            "properties": {
                "actual": {
                    "type": "integer",
                    "example": 4
                },
                "next": {
                    "type": "integer",
                    "example": 6
                },
                "previous": {
                    "type": "integer",
                    "example": 5
                },
                "size": {
                    "type": "integer",
                    "example": 5
                },
                "total_objects": {
                    "type": "integer",
                    "example": 100
                },
                "total_pages": {
                    "type": "integer",
                    "example": 20
                }
            }
        },
        "serializers.paginatedAppsSerializerMeta": {
            "type": "object",
            "properties": {
                "cursor": {
                    "$ref": "#/definitions/serializers.CursorSerializer"
                }
            }
        },
        "serializers.userDataSerializer": {
            "type": "object",
            "properties": {
                "birthday": {
                    "type": "string",
                    "example": "1997-12-21"
                },
                "email": {
                    "type": "string",
                    "example": "test@test.com"
                },
                "name": {
                    "type": "string",
                    "example": "John"
                },
                "phone": {
                    "type": "string",
                    "example": "+34666123456"
                },
                "surname": {
                    "type": "string",
                    "example": "Doe"
                },
                "uuid": {
                    "type": "string",
                    "example": "4722679b-5a48-4e85-9084-605e8df610f4"
                }
            }
        },
        "validators.AppCreateData": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "icon_url": {
                    "type": "string",
                    "example": "http://youriconurl.dev"
                },
                "name": {
                    "type": "string",
                    "example": "MySuperApp"
                },
                "redirect_urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "http://yourredirecturl.dev"
                    ]
                }
            }
        },
        "validators.AuthTokens": {
            "type": "object",
            "required": [
                "access_token",
                "refresh_token"
            ],
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
                },
                "refresh_token": {
                    "type": "string",
                    "example": "kpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyf"
                }
            }
        },
        "validators.Credentials": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "My@appPassw0rd"
                }
            }
        },
        "validators.OauthAuthorizeData": {
            "type": "object",
            "required": [
                "client_id",
                "redirect_uri",
                "scopes"
            ],
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "4722679b-5a48-4e85-9084-605e8df610f4"
                },
                "redirect_uri": {
                    "type": "string",
                    "example": "http://yourredirecturl.dev"
                },
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "user:read"
                    ]
                },
                "state": {
                    "type": "string",
                    "example": "iuywerghiuhg3487"
                }
            }
        },
        "validators.OauthExchangeToken": {
            "type": "object",
            "required": [
                "client_id",
                "client_secret",
                "code",
                "grant_type",
                "redirect_uri"
            ],
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "4722679b-5a48-4e85-9084-605e8df610f4"
                },
                "client_secret": {
                    "type": "string",
                    "example": "3i4u5h234ui5234bniuoo4i55543oi5jhio"
                },
                "code": {
                    "type": "string",
                    "example": "iwuqebgrfweiur4"
                },
                "grant_type": {
                    "type": "string",
                    "example": "authorization_code"
                },
                "redirect_uri": {
                    "type": "string",
                    "example": "http://callback"
                }
            }
        },
        "validators.UserCreateData": {
            "type": "object",
            "required": [
                "birthday",
                "email",
                "name",
                "password",
                "surname"
            ],
            "properties": {
                "birthday": {
                    "type": "string",
                    "example": "1997-12-21"
                },
                "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "John"
                },
                "password": {
                    "type": "string",
                    "example": "My@appPassw0rd"
                },
                "phone": {
                    "type": "string",
                    "example": "+34666123456"
                },
                "surname": {
                    "type": "string",
                    "example": "Doe"
                }
            }
        },
        "validators.UserResendEmail": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                }
            }
        },
        "validators.UserUpdateData": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "My@appPassw0rd"
                },
                "phone": {
                    "type": "string",
                    "example": "+34666123456"
                }
            }
        }
    },
    "securityDefinitions": {
        "OAuth2AccessCode": {
            "type": "oauth2",
            "flow": "accessCode",
            "authorizationUrl": "http://localhost:3000/oauth",
            "tokenUrl": "http://localhost:9100/oauth/token",
            "scopes": {
                "app:me:read": " Grants access to read self created apps",
                "app:me:write": " Grants access to write self created apps",
                "user:me:authorized-app": " Grants access an app to get information about the user",
                "user:me:change-password": " Grants access to change self password",
                "user:me:delete": " Grants access to delete self user",
                "user:me:read": " Grants access to read self user",
                "user:me:verify": " Grants access to verify created user",
                "user:me:write": " Grants access to write self user"
            }
        }
    },
    "x-extension-openapi": {
        "example": "value on a json format"
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:9100",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Gandalf API",
	Description: "Oauth2 server.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
