definitions:
  helpers.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      error:
        example: status bad request
        type: string
    type: object
  serializers.UserSerializer:
    properties:
      data:
        $ref: '#/definitions/serializers.userDataSerializer'
      type:
        example: user
        type: string
    type: object
  serializers.userDataSerializer:
    properties:
      birthday:
        example: "1997-12-21"
        type: string
      email:
        example: test@test.com
        type: string
      name:
        example: John
        type: string
      phone:
        example: "+34666123456"
        type: string
      surname:
        example: Doe
        type: string
      uuid:
        example: 4722679b-5a48-4e85-9084-605e8df610f4
        type: string
    type: object
  validators.UserCreateData:
    properties:
      birthday:
        example: "1997-12-21"
        type: string
      email:
        example: johndoe@example.com
        type: string
      name:
        example: John
        type: string
      password:
        example: My@appPassw0rd
        type: string
      phone:
        example: "+34666123456"
        type: string
      surname:
        example: Doe
        type: string
    required:
    - birthday
    - email
    - name
    - password
    - surname
    type: object
host: localhost:9100
info:
  contact: {}
  description: Oauth2 server.
  title: Gandalf API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Creates a new user
      operationId: create-user
      parameters:
      - description: Creates a new user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/validators.UserCreateData'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/serializers.UserSerializer'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.HTTPError'
      summary: Creates a new user
swagger: "2.0"
x-extension-openapi:
  example: value on a json format
